### PR TITLE
Fix alignment and remove scrolling from most screens

### PR DESCRIPTION
**Pull request by leonm1**
summary of changes:

- [x] vertically align all content on page
- [x] make padding uniform surrounding the dots
- [x] add a border-radius to the text fields
- [x] add padding of 4px between text fields
- [x] stack text input fields
- [x] add light white background to input fields
- [x] make more responsive by removing scrolling from basically screen size (yay!)
- [x] display the full logo on landscape mode in mobile devices
- [x] fix background color so screens with resolutions larger than the png fill with the png's bg color
- [x] horizontal layout on desktop
- [x] make layout stack on small screens
- [x] remove background on phones
- [x] fix a metric ton of layout bugs on small devices

### CODE REVIEW

**Review by cktang88 — CHANGES_REQUESTED** [review]
image

On smaller screens, the MLH logo covers the input fields. Perhaps move the MLH logo to the left, or move input fields down a bit?

**Comment by cktang88** [comment]
Also, vertically center "Get Notified"?

**Comment by leonm1** [comment]
I am not sure what configurations you are trying, so I need more information to recreate them. I tried on three different laptops and every mobile device compatibility mode chrome has. None of these layout issues exist there. What is the viewbox size?

**Comment by cktang88** [comment]
`window.innerWidth` is 841, `window.innerHeight` is 575, firefox, 1920x1080 native resolution

**Review by cktang88 — APPROVED** [review]

**Pull request merged**
